const toggle=document.querySelector('.mobile-toggle');
const sidebar=document.querySelector('.sidebar');
toggle?.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));sidebar?.classList.toggle('open',!open)});
document.querySelectorAll('.sidebar a').forEach(link=>link.addEventListener('click',()=>{sidebar?.classList.remove('open');toggle?.setAttribute('aria-expanded','false')}));

const translations={
  zh:{site:'刘佳庚',title:'副教授 刘佳庚',navHome:'主页',navContact:'联系方式',navBio:'个人简介',navResearch:'研究方向',navPubs:'论文成果',navPatents:'发明专利',navTeaching:'课程介绍',navServiceGroup:'学术兼职',navService:'学术兼职',profile:'博士，副教授、硕士生导师<br />电气工程师，电工高级技师，心理咨询师',profileSchool:'沈阳理工大学 装备工程学院<br />信息对抗专业专任教师',bioTitle:'个人简介',researchTitle:'研究方向',teachingTitle:'课程介绍',undergrad:'本科生课程',grad:'研究生课程',pubTitle:'论文成果',pubNote:'论文清单（点击标题进入论文网页）',patentTitle:'发明专利',patentNote:'中国发明专利（含已授权及已公开，点击标题进入公开网页）',serviceTitle:'学术兼职',contactTitle:'联系方式',address:'沈阳理工大学 装备工程学院<br />辽宁省沈阳市浑南区南屏中路 6 号',email:'联系邮箱：',footer:'© 刘佳庚 · Shenyang Ligong University'},
  en:{site:'Jiageng Liu',title:'Associate Professor Jiageng Liu',navHome:'Home',navContact:'Contact',navBio:'Biography',navResearch:'Research Areas',navPubs:'Publications',navPatents:'Patents',navTeaching:'Teaching',navServiceGroup:'Academic Appointments',navService:'Academic Appointments',profile:'Associate Professor, Master’s Supervisor<br />Electrical Engineer, Senior Electrical Technician, Psychological Counselor',profileSchool:'School of Equipment Engineering, Shenyang Ligong University<br />Full-time Faculty, Information Confrontation',bioTitle:'Biography',researchTitle:'Research Areas',teachingTitle:'Teaching',undergrad:'Undergraduate Courses',grad:'Graduate Course',pubTitle:'Publications',pubNote:'Selected publications (click a title to open the article webpage)',patentTitle:'Patents',patentNote:'Chinese invention patents (granted and published; click a title to open the public webpage)',serviceTitle:'Academic Appointments',contactTitle:'Contact',address:'School of Equipment Engineering, Shenyang Ligong University<br />Shenyang, Liaoning, China',email:'Email: ',footer:'© Jiageng Liu · Shenyang Ligong University'}
};
const researchZh=['多传感器信息融合与组合导航理论','陆地车辆定位、运动状态估计与智能交通系统','智能车辆协同定位、目标跟踪与自主感知','信息对抗、定位完好性与故障/攻击检测','数学物理中的逆问题与非线性动力学'];
const researchEn=['Multi-sensor information fusion and integrated navigation theory','Land vehicle localization, motion-state estimation, and intelligent transportation systems','Cooperative localization, target tracking, and autonomous perception for intelligent vehicles','Information confrontation, localization integrity, and fault/attack detection','Inverse problems and nonlinear dynamics in mathematical physics'];
const coursesEn=[['Information Confrontation Principles','Intelligent Weapon Systems'],['Weapon Innovation Design and Practice (Control)'],['New Energy Vehicles (Skills Master Online Training Platform)']];
const patentsEn=['A Vehicle Fusion Localization System and Method in Complex Constrained Environments','A Vehicle Localization Integrity Monitoring Method and System Based on Residual Detection','A Scene-Classification-Based Navigation Method for Autonomous Vehicles','Adaptive Evaluation Method for Fault Detection, Identification, and Adaptation of Autonomous Vehicle Localization Integrity','A Localization Method Using Long-Term Evolution Received Signal Strength Indicators in Tunnel Environments','A Battery SOC Bias Drift Suppression Method and System','A Method for Identifying LPI Radar Signal Modulation Types','A Multi-Vehicle Cooperative Localization Device and Method Based on Intelligent Transportation Systems','A Multi-Sensor Multi-Vehicle Cooperative Localization System and Method Based on Adaptive Kernel Kalman Filtering'];
const additionalPatentsZh=[['一种电池SOC偏置漂移抑制方法及系统','CN122487936A','CN202610812250.8','2026-06-06','2026-07-31','刘佳庚；纪一凡；马泰阳；孙泰瑶'],['一种识别LPI雷达信号调制类型的方法','CN120779357A','CN202511007656.0','2025-07-22','2025-10-14','王恩德；刘佳庚；马泰阳'],['基于智能交通系统的多车辆协同定位装置及方法','CN118348516A','CN202410561232.8','2024-05-08','2024-07-16','郭戈；李增勃；刘佳庚；高振宇；柳妍希；董佳成'],['一种多传感器多车辆协同定位系统与方法','CN117250630A','CN202311110775.X','2023-08-31','2023-12-19','郭戈；林皓栋；刘佳庚；高振宇'],['基于自适应核卡尔曼滤波的多传感器融合定位系统及方法','CN117014815A','CN202310971302.2','2023-08-03','2023-11-07','郭戈；李增勃；刘佳庚；高振宇']];
const additionalPatentsEn=[['A Battery SOC Bias Drift Suppression Method and System','CN122487936A','CN202610812250.8','2026-06-06','2026-07-31','Jiageng Liu; Yifan Ji; Taiyang Ma; Suyao Sun'],['A Method for Identifying LPI Radar Signal Modulation Types','CN120779357A','CN202511007656.0','2025-07-22','2025-10-14','Ende Wang; Jiageng Liu; Taiyang Ma'],['A Multi-Vehicle Cooperative Localization Device and Method Based on Intelligent Transportation Systems','CN118348516A','CN202410561232.8','2024-05-08','2024-07-16','Ge Guo; Zengbo Li; Jiageng Liu; Zhenyu Gao; Yanxi Liu; Jiacheng Dong'],['A Multi-Sensor Multi-Vehicle Cooperative Localization System and Method','CN117250630A','CN202311110775.X','2023-08-31','2023-12-19','Ge Guo; Haodong Lin; Jiageng Liu; Zhenyu Gao'],['A Multi-Sensor Fusion Localization System and Method Based on Adaptive Kernel Kalman Filtering','CN117014815A','CN202310971302.2','2023-08-03','2023-11-07','Ge Guo; Zengbo Li; Jiageng Liu; Zhenyu Gao']];
const serviceEn=['Associate Editor, The International Journal of Intelligent Control and Systems','Youth Editorial Board Member, Journal of Artificial Intelligence and Control Systems','Reviewer, IEEE Trans. Instrum. Meas., IEEE Trans. Veh. Technol., IEEE Trans. Intell. Veh., IEEE Trans. Intell. Transp. Syst., and IEEE Intell. Transp. Syst. Mag.','Judge, New Energy Vehicle Intelligent Technology, the 2nd Vocational Skills Competition of Liaoning Province','Expert, National Graduate Education Evaluation and Monitoring Expert Database'];
const bioEn='Jiageng Liu is a Ph.D. candidate, Associate Professor, Master’s Supervisor, Electrical Engineer, Senior Electrical Technician, and Psychological Counselor. He graduated from Northeastern University with a major in Control Engineering and is a full-time faculty member in Information Confrontation at Shenyang Ligong University. His research interests include multi-sensor fusion, vehicle localization and tracking, information confrontation, and inverse problems and nonlinear dynamics in mathematical physics.';
const publicationDetails=[
  ['Ge Guo, Haodong Lin, Guangheng Liu, and Jiageng Liu','IEEE Transactions on Vehicular Technology, Early Access, 2026','IF 7.5; JCR Q1'],
  ['Yifan Ji, Ende Wang, and Jiageng Liu','IEEE Geoscience and Remote Sensing Letters, vol. 23, 2026','IF 4.8; JCR Q1'],
  ['Ende Wang, Taiyang Ma, Jiageng Liu, Yifan Ji, and Suyao Sun','IEEE Communications Letters, vol. 30, 2026','IF 4.5; JCR Q2'],
  ['Ge Guo, Guangheng Liu, and Jiageng Liu','IEEE Transactions on Instrumentation and Measurement, vol. 75, 2026','IF 7.0; JCR Q1'],
  ['Ge Guo, Zeng-Bo Li, and Jiageng Liu','IEEE Transactions on Vehicular Technology, vol. 75, no. 6, 2026','IF 7.5; JCR Q1'],
  ['Yaodong Wei, Jiageng Liu, Kejuan Xue, and Ende Wang','Defence Technology, 2026','IF 5.9; JCR Q1'],
  ['Jiageng Liu, Ge Guo, Xiaozheng Sun, Zengbo Li, and Haodong Lin','IEEE Transactions on Vehicular Technology, vol. 74, no. 4, 2025','IF 7.5; JCR Q1'],
  ['Ende Wang, Ziyao Chen, Jiageng Liu, and Boxuan Sun','Results in Engineering, vol. 28, article 108261, 2025','IF 7.9; JCR Q1'],
  ['Ge Guo, Xiaozheng Sun, and Jiageng Liu','IEEE Transactions on Vehicular Technology, vol. 73, no. 11, 2024','IF 7.5; JCR Q1'],
  ['Ge Guo, Jiageng Liu, and Xiaozheng Sun','IEEE Transactions on Vehicular Technology, vol. 72, no. 8, 2023','IF 7.5; JCR Q1'],
  ['Jiageng Liu, Ge Guo, and Renyongkang Zhang','IEEE Transactions on Vehicular Technology, vol. 72, no. 5, 2023','IF 7.5; JCR Q1'],
  ['Ge Guo and Jiageng Liu','IEEE Transactions on Instrumentation and Measurement, vol. 71, article 8500810, 2022','IF 7.0; JCR Q1'],
  ['Jiageng Liu and Ge Guo','IEEE Transactions on Instrumentation and Measurement, vol. 70, 2021','IF 7.0; JCR Q1']
];
const publicationRoles=['corresponding','third','third','third','corresponding','second','first','third','third','corresponding','first','second','first'];
function updatePublicationDetails(lang){
  const list=document.querySelector('#publications .publication-list');
  const items=[...list.querySelectorAll(':scope > li')];
  items.forEach((item,i)=>{if(!item.dataset.pubIndex)item.dataset.pubIndex=String(i)});
  const roleOrder=['first','corresponding','second','third','other'];
  items.sort((a,b)=>roleOrder.indexOf(publicationRoles[Number(a.dataset.pubIndex)])-roleOrder.indexOf(publicationRoles[Number(b.dataset.pubIndex)]));
  items.forEach(item=>{
    const i=Number(item.dataset.pubIndex); const [authors,details,metrics]=publicationDetails[i]||[]; if(!authors)return;
    const role=publicationRoles[i]||'other';
    if(!item.dataset.title){item.dataset.title=item.querySelector('a')?.textContent||'';item.dataset.href=item.querySelector('a')?.href||'#';item.dataset.venue=item.querySelector('.pub-venue')?.textContent||''}
    const title=item.dataset.title, href=item.dataset.href, venue=item.dataset.venue, rest=details.replace(`${venue}, `,'');
    const names=authors.replace(/, and | and /g,', ').split(', ');
    const markedNames=names.map(name=>name==='Jiageng Liu'?`<strong>${lang==='en'?'J. Liu':'Jiageng Liu'}</strong>${role==='corresponding'?'*':''}`:lang==='en'?toIEEEName(name):name);
    const authorText=lang==='en'?(markedNames.length>1?`${markedNames.slice(0,-1).join(', ')}, and ${markedNames.at(-1)}`:markedNames[0]):markedNames.join('，');
    const citationBody=lang==='en'?`${authorText}, "<a href="${href}" target="_blank" rel="noopener">${title}</a>," ${venue}, ${rest}.`:`${authorText}. <a href="${href}" target="_blank" rel="noopener">${title}</a> [J]. ${venue}, ${rest}.`;
    item.innerHTML=`<span class="citation-index">[${items.indexOf(item)+1}]</span><span class="citation-text">${citationBody} <span class="pub-metrics">${metrics}</span></span>`;
    list.append(item);
  });
const marker=lang==='en'?'* Corresponding author':'* 通讯作者'; let markerEl=document.querySelector('.corresponding-note'); if(!markerEl){markerEl=document.createElement('p');markerEl.className='corresponding-note'} markerEl.textContent=marker; list.after(markerEl);
}
function toIEEEName(name){
  const parts=name.trim().split(/\s+/), surname=parts.pop(), initials=parts.join(' ').split(/\s+/).filter(Boolean).map(part=>part.includes('-')?`${part.split('-')[0][0]}.-${part.split('-')[1][0]}.`:`${part[0]}.`).join(' ');
  return `${initials} ${surname}`;
}
function setList(selector,items){document.querySelector(selector).innerHTML=items.map(item=>`<li>${item}</li>`).join('')}
function setLanguage(lang){
  const t=translations[lang]; document.documentElement.lang=lang==='en'?'en':'zh-CN'; document.title=lang==='en'?'Jiageng Liu | Academic Homepage':'刘佳庚 | 个人学术主页';
  document.querySelector('.site-title').textContent=t.site; document.querySelector('.mobile-bar strong').textContent=t.site; document.querySelector('h1').textContent=t.title;
  const nav=[t.navHome,t.navContact,t.navBio,t.navResearch,t.navPubs,t.navPatents,t.navTeaching,t.navService]; const navLinks=[...document.querySelectorAll('.sidebar nav a')]; navLinks.forEach((a,i)=>a.textContent=nav[i]); [...document.querySelectorAll('.nav-label')][0].textContent=lang==='en'?'Research': '研究'; [...document.querySelectorAll('.nav-label')][1].textContent=lang==='en'?'Teaching':'教学'; [...document.querySelectorAll('.nav-label')][2].textContent=t.navServiceGroup;
  const profile=document.querySelector('.profile'); profile.classList.toggle('en-mode',lang==='en');
  document.querySelector('.profile-text').innerHTML=lang==='en'
    ? `<a class="name-link" href="#home">Jiageng Liu</a><p class="profile-role">Associate Professor, Master’s Supervisor<br />Electrical Engineer, Senior Electrical Technician, Psychological Counselor</p><p class="profile-affiliation">School of Equipment Engineering, Shenyang Ligong University<br />Full-time Faculty, Information Confrontation</p>`
    : `<a class="name-link" href="#home">${t.site}</a><p>${t.profile}</p><p>${t.profileSchool}</p>`;
  const sections=[['biography',t.bioTitle],['research',t.researchTitle],['teaching',t.teachingTitle],['publications',t.pubTitle],['patents',t.patentTitle],['service',t.serviceTitle],['contact',t.contactTitle]]; sections.forEach(([id,label])=>document.querySelector(`#${id} h2`).textContent=label);
  document.querySelector('#biography').innerHTML=`<h2>${t.bioTitle}</h2><p>${lang==='en'?bioEn:'刘佳庚，博士，副教授、硕士生导师，电气工程师，电工高级技师，心理咨询师，毕业于东北大学控制工程专业，现为装备工程学院信息对抗专业专任教师。主要从事多传感器融合、车辆定位、跟踪、信息对抗等研究。'}</p><p>${lang==='en'?'In recent years, he has led or participated in six research projects funded by the National Natural Science Foundation of China, the Natural Science Foundation of Liaoning Province, and other programs. He has published more than ten SCI papers in international journals and holds seven invention patents. He has received awards for academic achievements, technological innovation, and teaching guidance.':'近年来，主持/参与国家自然科学基金、辽宁省自然科学基金等科研项目 6 项，在 IEEE 汇刊等国际期刊发表 SCI 论文 10 余篇，发明专利 7 项；曾获辽宁省自然科学学术成果奖、科技创新奖、大学生创新创业大赛优秀指导教师、辽宁省技能大赛优秀指导教师、辽宁省教学信息化大赛二等奖。'}</p><p>${lang==='en'?'He currently serves as Associate Editor of <em>The International Journal of Intelligent Control and Systems</em>, a Youth Editorial Board Member of <em>Journal of Artificial Intelligence and Control Systems</em>, and a reviewer for five IEEE journals.':'现担任国际期刊 <em>The International Journal of Intelligent Control and Systems</em> 副主编（Associate Editor），<em>Journal of Artificial Intelligence and Control Systems</em> 青年编委，<em>IEEE Trans. Instrum. Meas.</em>、<em>IEEE Trans. Veh. Technol.</em>、<em>IEEE Trans. Intell. Veh.</em>、<em>IEEE Trans. Intell. Transp. Syst.</em>、<em>IEEE Intell. Transp. Syst. Mag.</em> 审稿人。'}</p>`;
  setList('#research .plain-list',lang==='en'?researchEn:researchZh);
  document.querySelector('#teaching').innerHTML=`<h2>${t.teachingTitle}</h2><div class="course-columns"><div><h3>${t.undergrad}</h3><ul class="plain-list"><li>${lang==='en'?coursesEn[0][0]:'《信息对抗原理》'}</li><li>${lang==='en'?coursesEn[0][1]:'《智能武器系统》'}</li></ul></div><div><h3>${t.grad}</h3><ul class="plain-list"><li>${lang==='en'?coursesEn[1][0]:'《武器创新设计与实践（控制）》'}</li></ul></div><div><h3>${lang==='en'?'Professional Training':'职业技能培训'}</h3><ul class="plain-list"><li>${lang==='en'?coursesEn[2][0]:'《新能源汽车》（技能大师在线培训平台）'}</li></ul></div></div>`;
  document.querySelector('#publications .section-note').textContent=t.pubNote; document.querySelector('#patents .section-note').textContent=t.patentNote; updatePublicationDetails(lang);
  const oldPatentTitles=['A Vehicle Fusion Localization System and Method in Complex Constrained Environments','A Vehicle Localization Integrity Monitoring Method and System Based on Residual Detection','A Scene-Classification-Based Navigation Method for Autonomous Vehicles','Adaptive Evaluation Method for Fault Detection, Identification, and Adaptation of Autonomous Vehicle Localization Integrity','A Localization Method Using Long-Term Evolution Received Signal Strength Indicators in Tunnel Environments'];
  const oldPatentTitlesZh=['一种复杂受限环境中车辆融合定位系统及方法','一种基于残差检测的车辆定位完好性监测方法及系统','一种基于场景分类的自动驾驶车辆导航方法','自动驾驶定位完好性故障检测识别自适应评估方法','隧道环境下使用长期演进接收信号强度指示符的定位方法'];
  const oldPatentUrls=['CN114415224B','CN115291253B','CN115285143B','CN121384095B','CN117930132B'];
  const oldPatentYears=['2023','2023','2024','2026','2026'];
  const oldPatentItems=(lang==='en'?oldPatentTitles:oldPatentTitlesZh).map((title,i)=>({title,url:oldPatentUrls[i],year:oldPatentYears[i],meta:lang==='en'?`Granted Chinese invention patent · Granted · ${oldPatentUrls[i]} · ${i<2?'First inventor':'Inventor'}`:`中国发明专利 · 已授权 · ${oldPatentUrls[i]} · ${i<2?'第一发明人':'发明人'}`}));
  const newPatentItems=(lang==='en'?additionalPatentsEn:additionalPatentsZh).map(([title,pub,app,appDate,pubDate,inventors])=>({title,url:pub,year:appDate.slice(0,4),meta:lang==='en'?`Published Chinese invention patent · Publication No. ${pub} · Application No. ${app} · Filed ${appDate} · Published ${pubDate} · ${inventors.startsWith('Jiageng Liu')?'First inventor':'Inventor'}`:`中国发明专利 · 已公开 · 公开号 ${pub} · 申请号 ${app} · 申请日 ${appDate} · 公布日 ${pubDate} · ${inventors.startsWith('刘佳庚')?'第一发明人':'发明人'}`}));
  setList('#patents .patent-list',[...oldPatentItems,...newPatentItems].map(item=>`<span>${item.year}</span><a href="https://patents.google.com/patent/${item.url}/zh" target="_blank" rel="noopener">${item.title}</a><small>${item.meta}</small>`));
  setList('#service .plain-list',lang==='en'?serviceEn:['《The International Journal of Intelligent Control and Systems》副主编（Associate Editor）','《Journal of Artificial Intelligence and Control Systems》青年编委','《IEEE Trans. Instrum. Meas.》《IEEE Trans. Veh. Technol.》《IEEE Trans. Intell. Veh.》《IEEE Trans. Intell. Transp. Syst.》《IEEE Intell. Transp. Syst. Mag.》审稿人','辽宁省第二届职业技能大赛“新能源汽车智能化技术”项目裁判员','全国研究生教育评估监测专家库专家']);
  document.querySelector('#contact').innerHTML=`<h2>${t.contactTitle}</h2><p>${t.address}</p><p>${t.email}<a href="mailto:liu331453318@163.com">liu331453318@163.com</a>；<a href="mailto:jiagengliu@sylu.edu.cn">jiagengliu@sylu.edu.cn</a></p>`; document.querySelector('footer').textContent=t.footer;
  document.querySelector('[data-lang="zh"]').textContent=lang==='en'?'Simplified Chinese':'简体中文'; document.querySelector('[data-lang="en"]').textContent='English'; document.querySelectorAll('.language-button').forEach(btn=>btn.classList.toggle('active',btn.dataset.lang===lang)); localStorage.setItem('site-language',lang);
}
document.querySelectorAll('.language-button').forEach(btn=>btn.addEventListener('click',()=>setLanguage(btn.dataset.lang)));
setLanguage(localStorage.getItem('site-language')||'zh');
